import React, { useState, useEffect } from 'react';
import { Editor } from './components/Editor';
import { Preview } from './components/Preview';
import { PresentationMode } from './components/PresentationMode';
import { renderMarp } from './utils/marp';
import { savePresentation, getAllPresentations, deletePresentation } from './utils/storage';
import { Presentation as PresentationIcon, LayoutTemplate, Download, Save, FileText, Trash2, Plus, Wand2, X, Maximize } from 'lucide-react';

const INITIAL_MARKDOWN = `---
theme: default
paginate: true
---

# Hello Marp!

This is a **rich** presentation builder.

---

## Features

- **Markdown** based
- **Real-time** preview
- **Export** to HTML/PDF
- **AI** powered (coming soon)

![bg right](https://picsum.photos/800/600)
`;

function App() {
  const [markdown, setMarkdown] = useState(INITIAL_MARKDOWN);
  const [preview, setPreview] = useState({ html: '', css: '' });
  const [currentId, setCurrentId] = useState<string>(() => crypto.randomUUID());
  const [savedFiles, setSavedFiles] = useState<any[]>([]);
  const [showSidebar, setShowSidebar] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [showAIModal, setShowAIModal] = useState(false);
  const [showPresentationMode, setShowPresentationMode] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');

  useEffect(() => {
    const { html, css } = renderMarp(markdown);
    setPreview({ html, css });
  }, [markdown]);

  useEffect(() => {
    loadFileList();
  }, []);

  const loadFileList = async () => {
    const files = await getAllPresentations();
    setSavedFiles(files.reverse());
  };

  const handleSave = async () => {
    const title = markdown.split('\n').find(line => line.startsWith('# '))?.replace('# ', '') || 'Untitled Presentation';
    await savePresentation({
      id: currentId,
      title,
      content: markdown,
      updatedAt: Date.now(),
    });
    await loadFileList();
  };

  const handleLoad = (file: any) => {
    setCurrentId(file.id);
    setMarkdown(file.content);
    setShowSidebar(false);
  };

  const handleNew = () => {
    setCurrentId(crypto.randomUUID());
    setMarkdown(INITIAL_MARKDOWN);
  };

  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    await deletePresentation(id);
    await loadFileList();
    if (currentId === id) {
      handleNew();
    }
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    downloadFile(markdown, 'presentation.md', 'text/markdown');
    setShowExportMenu(false);
  };

  const handleExportHTML = () => {
    const fullHTML = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Marp Presentation</title>
<style>
${preview.css}
body { margin: 0; background: #1e293b; }
</style>
</head>
<body>
${preview.html}
</body>
</html>`;
    downloadFile(fullHTML, 'presentation.html', 'text/html');
    setShowExportMenu(false);
  };

  const handleAIGenerate = () => {
    // Mock AI generation
    const newSlide = `
---

# ${aiPrompt}

Generated by AI...

- Point 1
- Point 2
- Point 3
`;
    setMarkdown(markdown + newSlide);
    setShowAIModal(false);
    setAiPrompt('');
  };

  return (
    <div className="h-screen w-screen flex flex-col bg-[var(--bg-primary)] p-4 gap-4">
      {/* Header */}
      <header className="h-16 glass-panel rounded-xl flex items-center justify-between px-6 shrink-0 z-10 relative">
        <div className="flex items-center gap-3">
          <button onClick={() => setShowSidebar(!showSidebar)} className="btn btn-ghost p-2">
            <PresentationIcon className="text-[var(--accent-primary)]" size={24} />
          </button>
          <h1 className="text-xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
            Marp Builder
          </h1>
        </div>

        <div className="flex items-center gap-2">
          <button className="btn btn-ghost" onClick={() => setShowAIModal(true)}>
            <Wand2 size={18} className="text-purple-400" />
            AI Generate
          </button>
          <div className="h-6 w-px bg-[var(--border-color)] mx-2" />
          <button className="btn btn-ghost" onClick={handleNew}>
            <Plus size={18} />
            New
          </button>
          <button className="btn btn-ghost">
            <LayoutTemplate size={18} />
            Templates
          </button>
          <button className="btn btn-ghost" onClick={handleSave}>
            <Save size={18} />
            Save
          </button>
          <div className="relative">
            <button className="btn btn-primary" onClick={() => setShowExportMenu(!showExportMenu)}>
              <Download size={18} />
              Export
            </button>
            {showExportMenu && (
              <div className="absolute right-0 top-full mt-2 w-48 glass-panel rounded-lg flex flex-col p-1 z-50 animate-in fade-in zoom-in-95 duration-100">
                <button onClick={handleExportMarkdown} className="btn btn-ghost justify-start w-full text-sm">
                  Markdown (.md)
                </button>
                <button onClick={handleExportHTML} className="btn btn-ghost justify-start w-full text-sm">
                  HTML (.html)
                </button>
                <button onClick={() => { window.print(); setShowExportMenu(false); }} className="btn btn-ghost justify-start w-full text-sm">
                  Print / PDF
                </button>
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex gap-4 min-h-0 relative">
        {/* Sidebar */}
        {showSidebar && (
          <div className="absolute left-0 top-0 bottom-0 w-64 glass-panel rounded-xl z-20 flex flex-col p-4 gap-2 animate-in slide-in-from-left duration-200">
            <h2 className="text-lg font-semibold mb-2">My Presentations</h2>
            <div className="flex-1 overflow-y-auto flex flex-col gap-2">
              {savedFiles.map(file => (
                <div
                  key={file.id}
                  onClick={() => handleLoad(file)}
                  className={`p-3 rounded-lg cursor-pointer flex items-center justify-between group transition-colors ${currentId === file.id ? 'bg-[var(--accent-primary)] text-white' : 'hover:bg-[var(--bg-tertiary)]'}`}
                >
                  <div className="flex items-center gap-2 overflow-hidden">
                    <FileText size={16} className="shrink-0" />
                    <span className="truncate text-sm">{file.title}</span>
                  </div>
                  <button
                    onClick={(e) => handleDelete(e, file.id)}
                    className="opacity-0 group-hover:opacity-100 p-1 hover:bg-red-500/20 hover:text-red-400 rounded transition-all"
                  >
                    <Trash2 size={14} />
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* AI Modal */}
        {showAIModal && (
          <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="w-[500px] glass-panel rounded-xl p-6 flex flex-col gap-4 shadow-2xl">
              <div className="flex items-center justify-between">
                <h2 className="text-xl font-bold flex items-center gap-2">
                  <Wand2 className="text-purple-400" />
                  AI Slide Generator
                </h2>
                <button onClick={() => setShowAIModal(false)} className="btn btn-ghost p-1">
                  <X size={20} />
                </button>
              </div>
              <textarea
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="Describe the slide you want to generate..."
                className="w-full h-32 bg-[var(--bg-secondary)] border border-[var(--border-color)] rounded-lg p-3 text-[var(--text-primary)] focus:outline-none focus:border-[var(--accent-primary)] resize-none"
              />
              <div className="flex justify-end gap-2">
                <button onClick={() => setShowAIModal(false)} className="btn btn-ghost">Cancel</button>
                <button onClick={handleAIGenerate} className="btn btn-primary bg-gradient-to-r from-blue-500 to-purple-600 border-none">
                  Generate
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Editor Pane */}
        <div className="flex-1 min-w-0 flex flex-col gap-2">
          <div className="flex items-center justify-between px-2">
            <span className="text-sm font-medium text-[var(--text-secondary)]">Editor</span>
          </div>
          <Editor value={markdown} onChange={setMarkdown} />
        </div>

        {/* Preview Pane */}
        <div className="flex-1 min-w-0 flex flex-col gap-2">
          <div className="flex items-center justify-between px-2">
            <span className="text-sm font-medium text-[var(--text-secondary)]">Preview</span>
            <button
              onClick={() => setShowPresentationMode(true)}
              className="btn btn-ghost p-2 text-xs"
              title="Presentation Mode (Fullscreen)"
            >
              <Maximize size={16} />
              Present
            </button>
          </div>
          <Preview html={preview.html} css={preview.css} />
        </div>
      </main>

      {/* Presentation Mode */}
      {showPresentationMode && (
        <PresentationMode
          html={preview.html}
          css={preview.css}
          onClose={() => setShowPresentationMode(false)}
        />
      )}
    </div>
  );
}

export default App;
